<!DOCTYPE html>
<html lang="en">
<head>
 <meta charset="UTF-8">
 <meta name="viewport" content="width=device-width, initial-scale=1.0">
 <title>Explorando Tags HTML</title>
</head>
<body>
 <h1>Tags de Cabeçalho</h1>
 <p>O Lorem Ipsum é simplesmente uma simulação de texto da indústria tipográfica e
de impressos.</p>
 <h2>Tags de Parágrafo</h2>
 <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean nec ex a magna
elementum porttitor. Pellentesque posuere malesuada accumsan. Suspendisse nec ante
libero. Ut at purus vitae leo posuere convallis. Duis auctor venenatis sapien.
Vivamus interdum, leo non sollicitudin condimentum, elit arcu consectetur odio, ut
congue ipsum tortor eget dui. Lorem ipsum dolor sit amet, consectetur adipiscing
elit. Quisque sodales, nunc non viverra maximus, dolor erat imperdiet enim, ac
consequat nisl lacus in enim. Aenean nec tempus massa.</p>
 <p>Vestibulum iaculis nisi in ipsum ullamcorper, ultrices gravida nisl dictum.
Duis vitae facilisis lacus, vitae commodo velit. Proin hendrerit, ex non aliquam
ultricies, arcu massa lobortis lectus, at laoreet dolor tortor non lorem. Vestibulum
aliquam leo sed enim sodales, non commodo nunc facilisis. Nunc sapien turpis,
suscipit venenatis dapibus sed, volutpat eget neque. Etiam hendrerit justo at magna
porta, varius cursus sapien cursus. Morbi aliquam nisl nec sagittis vehicula. Fusce
porta hendrerit tellus, vel facilisis sem fringilla nec. Vivamus eros orci, hendrerit
eu feugiat at, ornare vitae felis. Aenean in fermentum sem, nec vehicula diam.
Suspendisse facilisis pharetra purus, vel ornare leo congue nec.</p>
 <h3>Tags de Quebra de Linha (br e hr)</h3>
 <p>Texto antes da quebra de linha.<br>Texto após a quebra de linha.</p>
 <hr>
 <p>Texto após a linha horizontal.</p>
 <h4>Tags de Formatação de Texto</h4>
 <p><strong>Texto em negrito</strong> utilizando a tag strong.</p>
 <p><em>Texto em itálico</em> utilizando a tag em.</p>
 <p><u>Texto sublinhado</u> utilizando a tag u.</p>
</body>
</html>.